#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn format

yarn check-format ||
(
    echo '🤢🤮🤢🤮 Its FOKING RAW - Your styling looks disgusting. 🤢🤮🤢🤮
            Prettier Check Failed. Run yarn format, add changes and try commit again.';
    false;
)

yarn lint:fix

yarn lint-staged

yarn check-types




